### PR TITLE
Add simple refresh button

### PR DESCRIPTION
**Pull request by qanonmap**
Instead of reloading the entire page contents, users can click a button to query for new posts only.

### CODE REVIEW

**Comment by QCodefag** [comment]
Why do you think it is bad to reload the entire page contents?
Is it too slow on some devices/connections?

**Comment by qntmpkts** [comment]
Sometimes, new live posts can disappear before they are added to the repo. This recheck, thus, prevents those posts from being lost from the browser. This is also why I wanted to make live posts have a different background, but you didn't merge that change to the css...

**Comment by qntmpkts** [comment]
Sometimes, new live posts can disappear before they are added to the repo. This recheck, thus, prevents those posts from being lost from the browser. This is also why I wanted to make live posts have a different background, but you didn't merge that change to the css...

**Comment by QCodefag** [comment]
>but you didn't merge that change to the css...

I've looked into this and see that you edited the .css file, which is the output of the corresponding .less file.
Changes to the .less file overwrite the .css file. So your thing got overwritten when I edited the .less file.
But I like your ideas.

I moved the status div to the bottom of the screen and because this was just such a small thing I  implemented your suggestions directly.

**Pull request closed without merging**
